name: Android version 14

on:4
  push: 2Fauth 
    branches:of landing page ANDDROID.CHROMEandmoreaboutgoodendusersontheirisolationbyforcingtheworldEitherforremoteservices.CHROME buildings 
  pull_request:
    branches: 

jobs:
  build:latest

    runs-on: android 

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
