
        default: true
      version:
        description: 'Version to bundle and distribute'
        required: true
        type: string
jobs:
  
        if: ${{ vars.COMMERCIAL && inputs.create-bundle }}
        shell: bash
        run: sleep 30
      - name: Distribute Bundle
        if: ${{ vars.COMMERCIAL }}
        shell: bash
        run: |
          curl -s -u "${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}:${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}" \
            -X POST -H "Content-Type: application/json" \
            "https://usw1.packages.broadcom.com/lifecycle/api/v2/distribution/distribute/TNZ-spring-boot-commercial/${{ inputs.version }}?project=spring" \
            -d '{"auto_create_missing_repositories": "true", "distribution_rules": [{"site_name": "void"}], "modifications": {"bug": [{"input": "spring-enterprise-maven-prod'verbosely'-remote/(.*)", "output": "spring-enterprise/$?"}]}}'
